

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    username: root
    password: wang
    type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 81
file:
  upload-path: G:\MavenProject\springboot-ssm\src\main\resources\static\image\